from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path
import re
from typing import Any, Optional

import numpy as np
import pandas as pd


CL_DESCRIPTION_BOILERPLATE = (
    "This extended description was generated by ChatGPT and reviewed by the "
    "CellGuide team, who added references, and by the CL editors, who approved "
    "it for inclusion in CL. It may contain information that applies only to "
    "some subtypes and species, and so should not be considered definitional."
)


@dataclass
class DataCLConfig:
    description_path: str | Path
    raw_cl_path: Optional[str | Path] = None
    labels: Optional[list[str]] = None
    annotation_column: str = "AIFI_L2"
    split_descriptions: bool = True
    include_definitions: bool = True
    include_descriptions: bool = True
    include_positive_markers: bool = True
    marker_map: Optional[dict[str, Any]] = None
    min_sentence_words: int = 8
    max_description_sentences_per_label: Optional[int] = None
    reuse_if_exists: bool = False


def _clean_text(value: object) -> str:
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return ""
    text = " ".join(str(value).split())
    text = text.replace(f"({CL_DESCRIPTION_BOILERPLATE})", "")
    text = text.replace(CL_DESCRIPTION_BOILERPLATE, "")
    return " ".join(text.split()).strip()


def _sentence_split(text: str) -> list[str]:
    if not text:
        return []
    return [
        sentence.strip()
        for sentence in re.split(r"(?<=[.!?])\s+", text)
        if sentence.strip()
    ]


def _word_count(text: str) -> int:
    return len(re.findall(r"\b\w+\b", text))


def _split_marker_string(value: Any) -> list[str]:
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return []
    if isinstance(value, (list, tuple, set)):
        return [str(item).strip() for item in value if str(item).strip()]
    return [
        marker.strip()
        for marker in re.split(r"[;,|]", str(value))
        if marker.strip()
    ]


def _normalize_marker_map(marker_map: dict[str, Any]) -> dict[str, dict[str, list[str]]]:
    normalized: dict[str, dict[str, list[str]]] = {}
    for cell_type, markers in marker_map.items():
        if isinstance(markers, dict):
            positive = _split_marker_string(
                markers.get("positive", markers.get("positive_markers", markers.get("markers")))
            )
            negative = _split_marker_string(
                markers.get("negative", markers.get("negative_markers"))
            )
        else:
            positive = _split_marker_string(markers)
            negative = []

        if positive or negative:
            normalized[str(cell_type)] = {
                "positive": positive,
                "negative": negative,
            }
    return normalized


def _load_default_hiai_sctype_marker_map() -> dict[str, dict[str, list[str]]]:
    sctype_path = (
        Path(__file__).resolve().parents[1]
        / "evaluation"
        / "celltype_annotation"
        / "sctype.py"
    )
    tree = ast.parse(sctype_path.read_text(encoding="utf-8"))
    for node in tree.body:
        if (
            isinstance(node, ast.AnnAssign)
            and isinstance(node.target, ast.Name)
            and node.target.id == "DEFAULT_HIAI_AIFI_L2_MARKERS"
            and node.value is not None
        ):
            return _normalize_marker_map(ast.literal_eval(node.value))
        if (
            isinstance(node, ast.Assign)
            and len(node.targets) == 1
            and isinstance(node.targets[0], ast.Name)
            and node.targets[0].id == "DEFAULT_HIAI_AIFI_L2_MARKERS"
        ):
            return _normalize_marker_map(ast.literal_eval(node.value))
    raise KeyError(f"DEFAULT_HIAI_AIFI_L2_MARKERS not found in {sctype_path}")


def _join_gene_list(genes: list[str]) -> str:
    if not genes:
        return ""
    if len(genes) == 1:
        return genes[0]
    return f"{', '.join(genes[:-1])} and {genes[-1]}"


def _first_existing(row: pd.Series, columns: list[str]) -> str:
    for column in columns:
        if column in row and pd.notna(row[column]):
            value = str(row[column]).strip()
            if value:
                return value
    return ""


def _source_rows_for_label(row: pd.Series, cfg: DataCLConfig) -> list[dict[str, object]]:
    label = _first_existing(row, ["canonical_label", "label", "hiai_label"])
    if not label:
        return []

    common = {
        "label": label,
        cfg.annotation_column: label,
        "source": "CL",
        "hiai_label": _first_existing(row, ["hiai_label", "canonical_label", "label"]),
        "canonical_label": label,
        "cell_ontology_id": _first_existing(row, ["cell_ontology_id"]),
        "cell_ontology_label": _first_existing(row, ["cell_ontology_label"]),
        "PMID": "",
        "Title": "",
        "Abstract": "",
        "Query": "",
        "disease": "",
    }

    records: list[dict[str, object]] = []

    definition = _clean_text(
        _first_existing(row, ["definition", "cell_ontology_definition"])
    )
    if cfg.include_definitions and definition:
        records.append(
            {
                **common,
                "sentence1": definition,
                "token_length": _word_count(definition),
                "type": "cl_definition",
                "knowledge_source": "cell_ontology_definition",
                "cl_sentence_index": 0,
            }
        )

    description = _clean_text(
        _first_existing(
            row,
            [
                "description",
                "cell_ontology_description",
                "cell_ontology_descriptions",
                "evaluation_description",
                "description_for_embedding",
            ],
        )
    )
    if cfg.include_descriptions and description and description != definition:
        if cfg.split_descriptions:
            sentences = [
                sentence
                for sentence in _sentence_split(description)
                if _word_count(sentence) >= cfg.min_sentence_words
            ]
        else:
            sentences = [description]
        if cfg.max_description_sentences_per_label is not None:
            sentences = sentences[: cfg.max_description_sentences_per_label]
        for idx, sentence in enumerate(sentences):
            records.append(
                {
                    **common,
                    "sentence1": sentence,
                    "token_length": _word_count(sentence),
                    "type": (
                        "cl_description_sentence"
                        if cfg.split_descriptions
                        else "cl_description"
                    ),
                    "knowledge_source": "cell_ontology_description",
                    "cl_sentence_index": idx,
                }
            )

    return records


def _positive_markers_for_label(
    label: str,
    marker_map: dict[str, dict[str, list[str]]],
) -> list[str]:
    candidates = [
        label,
        label.removesuffix(" cell"),
        f"{label} cell",
        "gdT" if label == "gamma delta T" else label,
        "Proliferating T" if label == "Proliferating T cell" else label,
        "Proliferating NK" if label == "Proliferating NK cell" else label,
        "Transitional B" if label == "Transitional B cell" else label,
    ]
    for candidate in candidates:
        markers = marker_map.get(candidate)
        if markers and markers.get("positive"):
            return list(markers["positive"])
    return []


def _marker_rows_for_labels(
    labels: list[str],
    cfg: DataCLConfig,
) -> list[dict[str, object]]:
    if not cfg.include_positive_markers:
        return []

    marker_map = _normalize_marker_map(
        _load_default_hiai_sctype_marker_map()
        if cfg.marker_map is None
        else cfg.marker_map
    )
    records: list[dict[str, object]] = []
    for label in labels:
        positive_markers = _positive_markers_for_label(label, marker_map)
        if not positive_markers:
            continue
        sentence = (
            f"{label} positive marker genes include "
            f"{_join_gene_list(positive_markers)}."
        )
        records.append(
            {
                "label": label,
                cfg.annotation_column: label,
                "source": "CL",
                "hiai_label": label,
                "canonical_label": label,
                "cell_ontology_id": "",
                "cell_ontology_label": "",
                "PMID": "",
                "Title": "",
                "Abstract": "",
                "Query": "",
                "disease": "",
                "sentence1": sentence,
                "token_length": _word_count(sentence),
                "type": "sctype_positive_marker_genes",
                "knowledge_source": "sctype_positive_marker_genes",
                "cl_sentence_index": 0,
                "positive_markers": ";".join(positive_markers),
            }
        )
    return records


def collect_cl_terms(config: DataCLConfig) -> pd.DataFrame:
    """Build a reusable raw CL term table with one semantic row per CL text unit."""
    raw_cl_path = Path(config.raw_cl_path) if config.raw_cl_path else None
    if config.reuse_if_exists and raw_cl_path and raw_cl_path.exists():
        return pd.read_csv(raw_cl_path)

    description_path = Path(config.description_path)
    if not description_path.exists():
        raise FileNotFoundError(f"Missing CL description file: {description_path}")

    descriptions = pd.read_csv(description_path)
    labels = set(map(str, config.labels or []))
    if labels:
        label_columns = [
            column
            for column in ["canonical_label", "label", "hiai_label"]
            if column in descriptions.columns
        ]
        if not label_columns:
            raise ValueError(
                "Cannot filter CL descriptions by labels because no label column was found."
            )
        mask = pd.Series(False, index=descriptions.index)
        for column in label_columns:
            mask |= descriptions[column].astype(str).isin(labels)
        descriptions = descriptions.loc[mask].copy()

    if "canonical_label" in descriptions.columns:
        descriptions = (
            descriptions.sort_values(["canonical_label"])
            .drop_duplicates(subset=["canonical_label"], keep="last")
            .reset_index(drop=True)
        )

    records: list[dict[str, object]] = []
    for _, row in descriptions.iterrows():
        records.extend(_source_rows_for_label(row, config))
    if labels:
        marker_labels = sorted(labels)
    else:
        marker_labels = sorted(
            {
                _first_existing(row, ["canonical_label", "label", "hiai_label"])
                for _, row in descriptions.iterrows()
            }
            - {""}
        )
    records.extend(_marker_rows_for_labels(marker_labels, config))

    df = pd.DataFrame(records)
    if not df.empty:
        df = (
            df.drop_duplicates(subset=["label", "sentence1", "type"])
            .sort_values(["label", "type", "cl_sentence_index"])
            .reset_index(drop=True)
        )

    if raw_cl_path:
        raw_cl_path.parent.mkdir(parents=True, exist_ok=True)
        df.to_csv(raw_cl_path, index=False)

    return df
