from __future__ import annotations

import argparse
from dataclasses import dataclass
import json
import logging
import os
from pathlib import Path
import sys
from typing import Any


PROJECT_ROOT = Path(__file__).resolve().parents[4]
os.environ.setdefault("MPLCONFIGDIR", str(PROJECT_ROOT / ".matplotlib"))
logging.getLogger("fontTools").setLevel(logging.WARNING)
logging.getLogger("fontTools.subset").setLevel(logging.WARNING)
logging.getLogger("matplotlib").setLevel(logging.WARNING)

SRC_DIR = PROJECT_ROOT / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))
HIAI_TCELLS_SCRIPT_DIR = PROJECT_ROOT / "scripts" / "revision1_v1" / "HIAI_Tcells"
if str(HIAI_TCELLS_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(HIAI_TCELLS_SCRIPT_DIR))

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

from alias.util.artifacts import write_metadata  # noqa: E402
from util.publication_plotting import (  # noqa: E402
    ABLATION_BAR_X_SPACING,
    AXIS_LABEL_SIZE,
    BAR_EDGE_COLOR,
    BAR_EDGE_LINEWIDTH,
    PAIRED_BAR_WIDTH,
    PLOT_HEIGHT,
    PUBLICATION_ABLATION_MODEL_ORDER,
    TICK_LABEL_SIZE,
    XTICK_ROTATION,
    ordered_present_models,
    publication_ablation_palette,
    publication_model_labels,
    save_publication_figure,
    set_publication_style,
)


DATASET_ID = "S2_heldout_donor_semantic_200k"
DATASET_DIR = PROJECT_ROOT / "out" / "data" / "revision1_v1" / "HIAI_Tcells" / DATASET_ID
SCRNA_TEST_PATH = DATASET_DIR / "datasets" / "scrna_test"
SCRNA_HF_DATASET = f"mariakrissmer/scrna_HIAI_Tcells_{DATASET_ID}"
EVALUATION_ROOT = DATASET_DIR / "evaluation_plots"
OUTPUT_DIR = DATASET_DIR / "functionality_assessment" / "mait_description_synonym"
EMBEDDING_ROOT = DATASET_DIR / "embeddings" / "mait_description_synonym"
ANNOTATION_COLUMN = "AIFI_L2"
TARGET_CELL_TYPE = "MAIT"
MAX_CELLS = int(os.environ.get("MAIT_FUNCTIONALITY_SYNONYM_MAX_CELLS", "20000"))
BATCH_SIZE = int(os.environ.get("MAIT_FUNCTIONALITY_SYNONYM_BATCH_SIZE", "256"))
TRUE_VARIANT_LABEL = "True description"
SYNONYM_VARIANT_LABEL = "Paraphrased description"


@dataclass(frozen=True)
class ModelSpec:
    label: str
    artifact_name: str
    model_id: str | Path
    fallback_artifact_names: tuple[str, ...] = ()


ABLATION_MODELS = [
    ModelSpec(
        label="MB",
        artifact_name="MB_HIAI_Tcells_S2_N1_200k_lr5e5_e15_epoch_15_ncbi",
        model_id=PROJECT_ROOT
        / "models"
        / "MB_HIAI_Tcells_S2_N1_200k_lr5e5_e15_all"
        / "epoch_15_ncbi",
        fallback_artifact_names=(
            "MB_HIAI_Tcells_S2_N1_200k_lr5e5_e15",
            "MB_HIAI_Tcells_S2_N1_200k_lr5e5",
            "MB_HIAI_Tcells_S2_N1",
        ),
    ),
    ModelSpec(
        label="MJ",
        artifact_name="MJ_HIAI_Tcells_S2_N3_200k_lr5e5",
        model_id="mariakrissmer/MJ_HIAI_Tcells_S2_N3_200k_lr5e5",
    ),
    ModelSpec(
        label="MG",
        artifact_name="MG_HIAI_Tcells_S2_200k_lr5e5_all",
        model_id=PROJECT_ROOT / "models" / "MG_HIAI_Tcells_S2_200k_lr5e5_all",
        fallback_artifact_names=("MG_HIAI_Tcells_S2_200k_lr5e5", "MG_HIAI_Tcells_S2_200k"),
    ),
    ModelSpec(
        label="MH",
        artifact_name="MH_HIAI_Tcells_S5_200k_lr5e5",
        model_id="mariakrissmer/MH_HIAI_Tcells_S5_200k_lr5e5",
    ),
    ModelSpec(
        label="MF",
        artifact_name="MF_HIAI_Tcells_S3_200k_lr5e5_all",
        model_id=PROJECT_ROOT / "models" / "MF_HIAI_Tcells_S3_200k_lr5e5_all",
        fallback_artifact_names=("MF_HIAI_Tcells_S3_200k_lr5e5", "MF_HIAI_Tcells_S3_200k"),
    ),
    ModelSpec(
        label="MI",
        artifact_name="MI_HIAI_Tcells_N1_200k_lr5e5_all",
        model_id=PROJECT_ROOT / "models" / "MI_HIAI_Tcells_N1_200k_lr5e5_all",
        fallback_artifact_names=("MI_HIAI_Tcells_N1_200k_lr5e5", "MI_HIAI_Tcells_N1_200k"),
    ),
    ModelSpec(
        label="Base",
        artifact_name="Base",
        model_id="neuml/pubmedbert-base-embeddings",
        fallback_artifact_names=("PubMedBERTBase", "pubmedbertbaseembeddings"),
    ),
]

TRUE_MAIT_DESCRIPTIONS = [
    "Recognize bacterial-derived riboflavin metabolites presented on MR1.",
    "Bridge innate and adaptive immunity with semi-invariant TCR and rapid cytokine output.",
]
MAIT_PARAPHRASES = {
    TRUE_MAIT_DESCRIPTIONS[0]: [
        "Detect bacterial riboflavin-derived metabolites displayed by MR1.",
        "Respond to microbial riboflavin metabolite antigens presented through MR1.",
        "Recognize MR1-presented metabolites generated by bacterial riboflavin biosynthesis.",
    ],
    TRUE_MAIT_DESCRIPTIONS[1]: [
        "Link innate and adaptive immune responses through a semi-invariant TCR and rapid cytokine production.",
        "Combine innate-like responsiveness with antigen-specific recognition via a semi-invariant TCR and fast cytokine release.",
        "Mediate rapid cytokine responses using a semi-invariant TCR at the interface of innate and adaptive immunity.",
    ],
}


def _env_bool(name: str, default: bool = False) -> bool:
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


FORCE_REGENERATE = _env_bool("MAIT_FUNCTIONALITY_SYNONYM_FORCE_REGENERATE", default=False)


def _timestamp_now() -> str:
    from datetime import datetime, timezone

    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H-%M-%S")


def _unique_run_dir(base_dir: Path) -> Path:
    if not base_dir.exists():
        return base_dir
    suffix = 1
    while True:
        candidate = base_dir.with_name(f"{base_dir.name}_{suffix:02d}")
        if not candidate.exists():
            return candidate
        suffix += 1


def _make_run_dir(output_dir: Path | str, timestamp: str | None = None) -> Path:
    run_dir = _unique_run_dir(Path(output_dir) / (timestamp or _timestamp_now()))
    run_dir.mkdir(parents=True, exist_ok=False)
    return run_dir


def mait_description_variants() -> pd.DataFrame:
    rows: list[dict[str, str]] = []
    for index, description in enumerate(TRUE_MAIT_DESCRIPTIONS, start=1):
        rows.append(
            {
                "description_id": f"true_{index}",
                "variant_type": "true",
                "source_description": description,
                "description_text": description,
                "target_cell_type": TARGET_CELL_TYPE,
            }
        )
    synonym_index = 1
    for source_description, paraphrases in MAIT_PARAPHRASES.items():
        for paraphrase in paraphrases:
            rows.append(
                {
                    "description_id": f"synonym_{synonym_index}",
                    "variant_type": "synonym",
                    "source_description": source_description,
                    "description_text": paraphrase,
                    "target_cell_type": TARGET_CELL_TYPE,
                }
            )
            synonym_index += 1
    return pd.DataFrame(
        rows,
        columns=[
            "description_id",
            "variant_type",
            "source_description",
            "description_text",
            "target_cell_type",
        ],
    )


def summarize_mait_auc(long_df: pd.DataFrame) -> pd.DataFrame:
    return (
        long_df.groupby(["model", "artifact_name", "variant_type"], as_index=False, sort=False)
        .agg(
            mean_roc_auc=("roc_auc", "mean"),
            sd_roc_auc=("roc_auc", "std"),
            n_descriptions=("description_id", "nunique"),
        )
        .loc[
            :,
            [
                "model",
                "artifact_name",
                "variant_type",
                "mean_roc_auc",
                "sd_roc_auc",
                "n_descriptions",
            ],
        ]
    )


def _select_models(model_names: list[str] | None = None) -> list[ModelSpec]:
    if not model_names:
        return ABLATION_MODELS
    requested = set(model_names)
    selected = [
        model
        for model in ABLATION_MODELS
        if model.label in requested or model.artifact_name in requested
    ]
    if not selected:
        raise ValueError(f"No configured MAIT functionality synonym models selected from: {model_names}")
    selected_order = ordered_present_models([model.label for model in selected])
    selected_by_label = {model.label: model for model in selected}
    return [selected_by_label[label] for label in selected_order if label in selected_by_label]


def _load_scrna_test():
    from datasets import load_from_disk
    from alias.util.load_hf_model import load_hf_dataset

    if SCRNA_TEST_PATH.exists():
        try:
            return load_from_disk(str(SCRNA_TEST_PATH))
        except Exception as error:
            print(
                f"Could not load local scrna_test from {SCRNA_TEST_PATH}: "
                f"{type(error).__name__}: {error}"
            )
            print(f"Falling back to Hugging Face dataset: {SCRNA_HF_DATASET}")

    dataset = load_hf_dataset(SCRNA_HF_DATASET)
    if isinstance(dataset, dict):
        for split_name in ("test", "scrna_test"):
            if split_name in dataset:
                return dataset[split_name]
        raise KeyError(
            f"Could not find a test split in {SCRNA_HF_DATASET}. "
            f"Available splits: {sorted(dataset.keys())}"
        )
    return dataset


def _model_source(model_id: str | Path) -> str | Path:
    model_path = Path(model_id)
    if model_path.exists():
        return model_path

    local_path = PROJECT_ROOT / "models" / str(model_id)
    if local_path.exists():
        return local_path

    return str(model_id)


def _rekey_embeddings_dict(embeddings_dict: dict, model_id: str | Path, artifact_name: str) -> dict:
    from alias.evaluation.embedding import clean_model_name

    source_key = clean_model_name(str(model_id))
    if source_key not in embeddings_dict:
        return embeddings_dict
    return {artifact_name: embeddings_dict[source_key]}


def _evaluate_model(
    model: ModelSpec,
    variants: pd.DataFrame,
    *,
    force_regenerate: bool = False,
) -> pd.DataFrame:
    from alias import evaluation as ev

    description_texts = variants["description_text"].astype(str).tolist()
    model_source = _model_source(model.model_id)
    print(f"Evaluating MAIT functionality descriptions for {model.label}: {model_source}")
    scrna_test = _load_scrna_test()
    embeddings_dict = ev.generate_embeddings(
        evaluation_dict={"scrna": {"test": scrna_test}},
        embedding_config=ev.GenEmbeddingsConfig(
            embedding_models=[str(model_source)],
            model_type="sentence_transformer",
            batch_size=BATCH_SIZE,
            output_dir=str(EMBEDDING_ROOT / model.artifact_name),
            max_cells=MAX_CELLS,
            annotation_column=ANNOTATION_COLUMN,
            additional_data=description_texts,
            force_regenerate=force_regenerate,
        ),
    )
    embeddings_dict = _rekey_embeddings_dict(
        embeddings_dict,
        model_id=model_source,
        artifact_name=model.artifact_name,
    )
    embeddings_dict = ev.umap_plots(
        embeddings_dict=embeddings_dict,
        annotation_column=ANNOTATION_COLUMN,
        output_dir=str(EVALUATION_ROOT),
        evaluation_config=ev.EvaluationConfig(
            n_neighbors=15,
            min_dist=0.5,
            random_state=21,
            n_components=25,
        ),
    )
    functionality_df = ev.functionality_similarity(
        embeddings_dict=embeddings_dict,
        annotation_column=ANNOTATION_COLUMN,
        config=ev.FunctionalitySimilarityConfig(
            similarity_metric="cosine",
            bins=60,
            output_dir=EVALUATION_ROOT,
            plot=True,
            true_label_map={
                description: TARGET_CELL_TYPE
                for description in description_texts
            },
        ),
    )
    model_df = functionality_df[
        functionality_df["cell_type"].astype(str) == TARGET_CELL_TYPE
    ].copy()
    variant_lookup = variants.set_index("description_text").to_dict(orient="index")
    model_df["description_text"] = model_df["functionality"].astype(str)
    model_df["description_id"] = model_df["description_text"].map(
        lambda value: variant_lookup[value]["description_id"]
    )
    model_df["variant_type"] = model_df["description_text"].map(
        lambda value: variant_lookup[value]["variant_type"]
    )
    model_df["source_description"] = model_df["description_text"].map(
        lambda value: variant_lookup[value]["source_description"]
    )
    model_df["target_cell_type"] = TARGET_CELL_TYPE
    model_df["model"] = model.label
    model_df["artifact_name"] = model.artifact_name
    return model_df[
        [
            "model",
            "artifact_name",
            "description_id",
            "variant_type",
            "source_description",
            "description_text",
            "target_cell_type",
            "cell_type",
            "mean_auc",
            "mean_cell_similarity",
            "median_cell_similarity",
            "label_embedding_similarity",
        ]
    ].rename(columns={"mean_auc": "roc_auc"})


def _plot_true_vs_synonym_auc(summary: pd.DataFrame, long_df: pd.DataFrame, output_dir: Path) -> None:
    set_publication_style()
    present_models = ordered_present_models(summary["model"].dropna().astype(str).unique())
    present_models = [model for model in PUBLICATION_ABLATION_MODEL_ORDER if model in set(present_models)]
    if not present_models:
        raise ValueError("No configured ablation models available to plot.")

    palette = publication_ablation_palette(present_models)
    variant_order = ["true", "synonym"]
    variant_labels = {
        "true": TRUE_VARIANT_LABEL,
        "synonym": SYNONYM_VARIANT_LABEL,
    }
    offsets = {"true": -PAIRED_BAR_WIDTH / 2, "synonym": PAIRED_BAR_WIDTH / 2}
    x_positions = {model: idx * ABLATION_BAR_X_SPACING for idx, model in enumerate(present_models)}

    fig, ax = plt.subplots(figsize=(3.2, PLOT_HEIGHT))
    rng = np.random.default_rng(42)
    for variant_type in variant_order:
        variant_df = summary[summary["variant_type"] == variant_type]
        heights = []
        errors = []
        positions = []
        colors = []
        for model in present_models:
            row = variant_df[variant_df["model"] == model]
            if row.empty:
                continue
            row = row.iloc[0]
            positions.append(x_positions[model] + offsets[variant_type])
            heights.append(float(row["mean_roc_auc"]))
            sd_value = row["sd_roc_auc"]
            errors.append(0.0 if pd.isna(sd_value) else float(sd_value))
            colors.append(palette[model])
        ax.bar(
            positions,
            heights,
            width=PAIRED_BAR_WIDTH,
            yerr=errors,
            color=colors,
            edgecolor=BAR_EDGE_COLOR,
            linewidth=BAR_EDGE_LINEWIDTH,
            capsize=2,
            label=variant_labels[variant_type],
            hatch="////" if variant_type == "synonym" else None,
            error_kw={"elinewidth": 0.6, "ecolor": "0.2", "capthick": 0.6},
        )
        if variant_type == "synonym":
            for patch in ax.patches[-len(positions):]:
                patch._hatch_color = (1, 1, 1, 1)

        point_df = long_df[long_df["variant_type"] == variant_type]
        for model in present_models:
            values = point_df.loc[point_df["model"] == model, "roc_auc"].astype(float).to_numpy()
            if len(values) == 0:
                continue
            jitter = rng.uniform(-0.025, 0.025, size=len(values))
            x_value = x_positions[model] + offsets[variant_type]
            ax.scatter(
                x_value + jitter,
                values,
                color="0.15",
                alpha=0.5,
                s=5,
                linewidths=0,
                zorder=3,
            )

    ax.set_xlabel("")
    ax.set_ylabel("ROC-AUC", fontsize=AXIS_LABEL_SIZE)
    ax.set_ylim(0, 1)
    ax.set_yticks(np.arange(0, 1.01, 0.2))
    ax.axhline(0.5, color="0.35", linestyle="--", linewidth=0.7, zorder=0)
    ax.set_xticks([x_positions[model] for model in present_models])
    ax.set_xticklabels(
        publication_model_labels(present_models),
        rotation=XTICK_ROTATION,
        ha="right",
        fontsize=TICK_LABEL_SIZE,
    )
    ax.tick_params(axis="x", which="major", bottom=True, length=3, width=0.7, color="0.2")
    ax.tick_params(axis="y", labelsize=TICK_LABEL_SIZE)
    if present_models:
        ax.set_xlim(
            x_positions[present_models[0]] - 0.34,
            x_positions[present_models[-1]] + 0.34,
        )
    ax.legend(frameon=False, fontsize=7, loc="upper right")
    sns.despine(ax=ax)
    save_publication_figure(
        fig,
        output_dir,
        "mait_true_vs_paraphrased_description_auc_ablation",
        formats=("pdf", "png", "svg"),
    )


def _json_safe_models(models: list[ModelSpec]) -> list[dict[str, Any]]:
    return [
        {
            "label": model.label,
            "artifact_name": model.artifact_name,
            "model_id": str(model.model_id),
            "fallback_artifact_names": list(model.fallback_artifact_names),
        }
        for model in models
    ]


def run(
    model_names: list[str] | None = None,
    *,
    force_regenerate: bool = FORCE_REGENERATE,
    timestamp: str | None = None,
) -> dict[str, Path]:
    variants = mait_description_variants()
    models = _select_models(model_names)
    run_dir = _make_run_dir(OUTPUT_DIR, timestamp=timestamp)

    variants_path = run_dir / "mait_functionality_description_variants.csv"
    variants.to_csv(variants_path, index=False)

    long_tables = [
        _evaluate_model(
            model,
            variants,
            force_regenerate=force_regenerate,
        )
        for model in models
    ]
    long_df = pd.concat(long_tables, ignore_index=True)
    summary = summarize_mait_auc(long_df)

    long_csv = run_dir / "mait_description_roc_auc_long.csv"
    summary_csv = run_dir / "mait_description_roc_auc_summary.csv"
    long_df.to_csv(long_csv, index=False)
    summary.to_csv(summary_csv, index=False)
    _plot_true_vs_synonym_auc(summary, long_df, run_dir)
    metadata_path = write_metadata(
        run_dir,
        {
            "evaluation_name": "mait_functionality_description_synonym_auc",
            "dataset_id": DATASET_ID,
            "dataset_dir": str(DATASET_DIR),
            "annotation_column": ANNOTATION_COLUMN,
            "target_cell_type": TARGET_CELL_TYPE,
            "max_cells": MAX_CELLS,
            "batch_size": BATCH_SIZE,
            "force_regenerate": force_regenerate,
            "models": _json_safe_models(models),
            "outputs": {
                "variants": str(variants_path),
                "long_results": str(long_csv),
                "summary": str(summary_csv),
                "plot_pdf": str(run_dir / "mait_true_vs_paraphrased_description_auc_ablation.pdf"),
                "plot_png": str(run_dir / "mait_true_vs_paraphrased_description_auc_ablation.png"),
                "plot_svg": str(run_dir / "mait_true_vs_paraphrased_description_auc_ablation.svg"),
            },
        },
    )
    return {
        "run_dir": run_dir,
        "variants_csv": variants_path,
        "long_csv": long_csv,
        "summary_csv": summary_csv,
        "metadata_json": metadata_path,
    }


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run MAIT true/paraphrased functionality description ROC-AUC ablation evaluation."
    )
    parser.add_argument(
        "--models",
        nargs="+",
        help="Optional model labels or artifact names to include, e.g. MB MG MI.",
    )
    parser.add_argument(
        "--force-regenerate",
        action="store_true",
        default=FORCE_REGENERATE,
        help="Force regeneration of embeddings for the MAIT description prompt set.",
    )
    parser.add_argument(
        "--timestamp",
        help="Optional timestamp/run-folder name for reproducible smoke tests.",
    )
    return parser.parse_args()


def main() -> None:
    args = _parse_args()
    outputs = run(
        model_names=args.models,
        force_regenerate=args.force_regenerate,
        timestamp=args.timestamp,
    )
    print(f"Saved MAIT functionality synonym ROC-AUC evaluation to {outputs['run_dir']}")


if __name__ == "__main__":
    main()
