
TEMPLATES = {
    'genes': [
        "A cell that expresses: {gene_str}.",
        "This cell expresses the genes: {gene_str}.",
        "Highly expressed genes: {gene_str}.",
        "Expression profile includes: {gene_str}.",
        "{gene_str} are the top expressed genes in this cell.",
        "Transcriptomic features: {gene_str}.",
        "Detected gene expression: {gene_str}.",
        "This cell shows significant expression of: {gene_str}.",
        "Key genes active in this cell: {gene_str}.",
        "The expression pattern includes: {gene_str}.",
        "Observed top genes: {gene_str}.",
        "The cell displays expression of: {gene_str}.",
        "Gene ranking includes: {gene_str}.",
        "High-ranking genes: {gene_str}.",
        "Based on transcriptomics, {gene_str} are key features.",
        "Top genes from expression profile: {gene_str}.",
        "Leading genes expressed: {gene_str}.",
        "This cell is characterized by expression of: {gene_str}.",
        "{gene_str} define the expression landscape of this cell.",
        "The active transcriptional program includes: {gene_str}."
        ],
    'genes_celltype': [
        "A cell that expresses the following genes: {gene_str} is likely a {cell_type} cell.",
        "This cell shows high expression of {gene_str}, suggesting it is a {cell_type}.",
        "Based on the expression of {gene_str}, this appears to be a {cell_type} cell.",
        "The genes {gene_str} are expressed in this cell, which is classified as a {cell_type}.",
        "{cell_type} cells typically express genes such as: {gene_str}.",
        "The combination of {gene_str} is characteristic for {cell_type} cells.",
        "This transcriptomic profile — with genes like {gene_str} — resembles that of a {cell_type}.",
        "A typical {cell_type} cell expresses the genes: {gene_str}.",
        "A {cell_type} signature includes: {gene_str}.",
        "The expression pattern of {gene_str} strongly indicates a {cell_type} cell.",
        "{gene_str} are commonly found in {cell_type} cells.",
        "Gene expression matches that of {cell_type} cells, including: {gene_str}.",
        "Cells expressing {gene_str} often belong to the {cell_type} lineage.",
        "The gene markers {gene_str} suggest this cell is a {cell_type}.",
        "These expression features — {gene_str} — are typical of a {cell_type} identity.",
        "Observed genes ({gene_str}) are indicative of {cell_type} cell function.",
        "With genes like {gene_str} active, this cell is identified as a {cell_type}.",
        "Expressing {gene_str}, this cell is consistent with {cell_type} identity.",
        "The cell’s transcriptome points to a {cell_type} lineage, with key genes like {gene_str}.",
        "This cell likely originates from the {cell_type} family, based on expression of {gene_str}.",
        "{cell_type} cells are known to express: {gene_str}.",
        "The expression of {gene_str} aligns with a {cell_type} identity.",
        "The transcriptome suggests a {cell_type} type, with expression of {gene_str}.",
        "Given {gene_str}, this cell can be classified as a {cell_type}.",
        "This profile resembles {cell_type} cells, based on genes like {gene_str}.",
        "The pattern {gene_str} is indicative of {cell_type} differentiation.",
        "Expression of {gene_str} suggests {cell_type} lineage commitment.",
        "Typical {cell_type} markers such as {gene_str} are present in this cell.",
        "This cell fits the molecular signature of {cell_type}, expressing {gene_str}.",
        "The transcriptomic signal ({gene_str}) matches a {cell_type} phenotype.",
        "The active genes {gene_str} align with a {cell_type} signature.",
        "Presence of {gene_str} supports classification as {cell_type}.",
        "{gene_str} expression pattern defines this as a {cell_type} cell.",
        "Consistent with {cell_type} function, genes like {gene_str} are expressed.",
        "This expression fingerprint ({gene_str}) marks a {cell_type} cell.",
        "{gene_str} expression places this cell in the {cell_type} category.",
        "According to gene expression ({gene_str}), this is a {cell_type}.",
        "A transcriptome with {gene_str} points toward {cell_type} identity.",
        "{gene_str} reflect the unique expression profile of {cell_type} cells.",
        "Genes like {gene_str} are hallmarks of {cell_type} cells."
        ],
    'genes_celltype_time': [
        "A cell that expresses the following genes: {gene_str} is likely a {cell_type} cell at {time}.",
        "A {cell_type} cell at {time} expresses these genes: {gene_str}.",
        "At {time}, a {cell_type} cell expresses the genes {gene_str}.",
        "The expression profile {gene_str} suggests a {cell_type} identity at {time}.",
        "Cells expressing {gene_str} at {time} are likely {cell_type} cells.",
        "A {cell_type} identified by the genes {gene_str} was observed at {time}.",
        "During {time}, this {cell_type} cell shows expression of {gene_str}.",
        "At {time}, expression of {gene_str} characterizes a {cell_type} cell.",
        "The gene set {gene_str} corresponds to a {cell_type} cell at {time}.",
        "{time}: A {cell_type} cell with gene expression of {gene_str}.",
        "A {cell_type} cell present at {time}, expressing {gene_str}.",
        "Cells found at {time} with {gene_str} expression match {cell_type} identity.",
        "At {time}, {cell_type} cells express genes including {gene_str}.",
        "{cell_type} cells at {time} exhibit expression of {gene_str}.",
        "The transcriptome {gene_str} is indicative of a {cell_type} cell at {time}.",
        "A {cell_type} cell, found at {time}, is marked by genes {gene_str}.",
        "Cells expressing {gene_str} at {time} most likely belong to the {cell_type} lineage.",
        "A {cell_type} cell at {time} expresses genes such as {gene_str}.",
        "At {time}, the cell expresses {gene_str} and is identified as a {cell_type}.",
        "At developmental stage {time}, this gene profile {gene_str} suggests a {cell_type} cell.",
        "This {cell_type} cell expresses {gene_str}, recorded at {time}.",
        "During {time}, expression of {gene_str} is seen in {cell_type} cells.",
        "{cell_type} cells are observed at {time} with genes like {gene_str} being expressed.",
        "{time} cells with gene expression {gene_str} are identified as {cell_type}.",
        "Observed at {time}, this cell expresses {gene_str} and is classified as a {cell_type}.",
        "{time}: cells with {gene_str} expression are labeled as {cell_type}.",
        "A {cell_type} cell from {time}, expressing genes like {gene_str}.",
        "With gene expression of {gene_str}, this {cell_type} cell was identified at {time}.",
        "Cells expressing {gene_str} at {time} likely differentiate into {cell_type}.",
        "{gene_str} expression at {time} indicates a {cell_type} identity.",
        "At embryonic stage {time}, {cell_type} cells express {gene_str}.",
        "A gene profile of {gene_str} suggests a {cell_type} cell collected at {time}.",
        "At {time}, this {cell_type} shows characteristic expression of {gene_str}.",
        "Cells with expression pattern {gene_str} found at {time} are classified as {cell_type}.",
        "A {cell_type} at {time} expresses a key set of genes: {gene_str}.",
        "Gene markers {gene_str} define a {cell_type} cell at {time}.",
        "A {cell_type} identity at {time} is inferred from expression of {gene_str}.",
        "Found at {time}, this {cell_type} cell expresses {gene_str}.",
        "The gene expression {gene_str} identifies a {cell_type} at {time}.",
        ],
    'genes_time': [
        "At {time}, the cell expresses the following genes: {gene_str}.",
        "This cell expresses {gene_str}, recorded at {time}.",
        "Gene expression profile {gene_str} observed at {time}.",
        "A cell expressing {gene_str} was found at {time}.",
        "During {time}, this cell shows expression of {gene_str}.",
        "At developmental stage {time}, the cell expresses {gene_str}.",
        "{time}: Cell with expression pattern {gene_str}.",
        "A cell with the gene set {gene_str} was captured at {time}.",
        "{time}: A single cell expresses {gene_str}.",
        "Observed at {time}, this cell expresses genes {gene_str}.",
        "During embryonic development at {time}, this cell expresses {gene_str}.",
        "At {time}, this gene expression profile {gene_str} was detected.",
        "Genes {gene_str} were expressed by a cell at {time}.",
        "A gene expression pattern of {gene_str} was seen at {time}.",
        "At {time}, cells with {gene_str} expression were present.",
        "The transcriptomic signature {gene_str} was recorded at {time}.",
        "At {time}, single-cell RNA-seq reveals expression of {gene_str}.",
        "Cells expressing {gene_str} were observed during {time}.",
        "A cell from {time} shows expression of {gene_str}.",
        "This cell, captured at {time}, expressed {gene_str}.",
        ],
    'genes_celltype_disease': [
        "A {cell_type} cell in {disease_status} expresses the following genes: {gene_str}.",
        "In {disease_status}, {cell_type} cells express {gene_str}.",
        "{cell_type} cells expressing {gene_str} are observed in {disease_status}.",
        "This {cell_type} cell expresses {gene_str} under {disease_status} conditions.",
        "Under {disease_status}, the gene expression profile {gene_str} indicates a {cell_type} identity.",
        "Cells with gene set {gene_str} in {disease_status} are likely {cell_type} cells.",
        "The genes {gene_str} are expressed by {cell_type} cells in the context of {disease_status}.",
        "{gene_str} expression in {disease_status} suggests a {cell_type} phenotype.",
        "A {cell_type} cell with expression of {gene_str} was found in {disease_status}.",
        "During {disease_status}, a {cell_type} cell expresses genes including {gene_str}.",
        "A {cell_type} expressing {gene_str} has been identified in {disease_status} tissue.",
        "{disease_status}-associated {cell_type} cells express {gene_str}.",
        "{cell_type} cells in samples from {disease_status} exhibit expression of {gene_str}.",
        "Expression of {gene_str} indicates {cell_type} identity in a {disease_status} condition.",
        "In {disease_status}, a {cell_type} cell displays this gene profile: {gene_str}.",
        "Observed in {disease_status}, this {cell_type} expresses {gene_str}.",
        "Gene expression {gene_str} defines a {cell_type} cell within {disease_status} context.",
        "A {cell_type} cell affected by {disease_status} expresses {gene_str}.",
        "{gene_str} are markers of a {cell_type} cell in {disease_status} samples.",
        "A cell expressing {gene_str} is identified as a {cell_type} in the setting of {disease_status}.",
        "This {cell_type} cell, collected from {disease_status} tissue, expresses {gene_str}.",
        "{gene_str} expression characterizes a {cell_type} cell in {disease_status} specimens.",
        "A {cell_type} cell from a patient with {disease_status} shows {gene_str} expression.",
        "In the presence of {disease_status}, this {cell_type} cell expresses {gene_str}.",
        "A {cell_type} cell isolated from {disease_status}-affected tissue expresses {gene_str}.",
        "With gene expression {gene_str}, this {cell_type} is found in {disease_status}.",
        "A {cell_type} expressing {gene_str} was observed in a {disease_status} context.",
        "{disease_status} alters gene expression in {cell_type} cells, showing {gene_str}.",
        "Cells of type {cell_type} in {disease_status} have a signature of {gene_str}.",
        "{gene_str} expression suggests {cell_type} function in {disease_status}.",
        "{disease_status}: {cell_type} cells expressing {gene_str}.",
        "Transcriptomic profiling in {disease_status} reveals {cell_type} expression of {gene_str}.",
        "The {cell_type} identity is supported by gene set {gene_str} in {disease_status}.",
        "{gene_str} genes are expressed in {cell_type} cells under {disease_status}.",
        "From a {disease_status} sample, this {cell_type} expresses {gene_str}.",
        "{cell_type} from {disease_status} condition expresses genes: {gene_str}.",
        "Observed gene expression {gene_str} in {disease_status} indicates {cell_type}.",
        "Affected by {disease_status}, this {cell_type} expresses {gene_str}.",
        "{gene_str} is a disease-associated expression profile of a {cell_type} cell in {disease_status}.",
        "A {cell_type} cell with this gene profile {gene_str} was identified in {disease_status}.",
        ],
    'genes_disease': [
        "A cell expresses {gene_str} in the context of {disease_status}.",
        "Under {disease_status} conditions, this cell expresses {gene_str}.",
        "Cells in {disease_status} tissue express genes including {gene_str}.",
        "In {disease_status}, gene expression includes {gene_str}.",
        "Observed in {disease_status}, this cell expresses {gene_str}.",
        "During {disease_status}, the following genes are expressed: {gene_str}.",
        "{gene_str} expression is associated with {disease_status}.",
        "The gene set {gene_str} is expressed in cells affected by {disease_status}.",
        "A cell in {disease_status} shows gene expression pattern: {gene_str}.",
        "{gene_str} were expressed in a cell from {disease_status} tissue.",
        "This cell expresses {gene_str} under {disease_status}.",
        "In the context of {disease_status}, the cell exhibits expression of {gene_str}.",
        "A {disease_status} sample contains cells with {gene_str} expression.",
        "The transcriptomic signature {gene_str} was found in {disease_status}.",
        "Cells collected from {disease_status} condition show expression of {gene_str}.",
        "{disease_status}-associated gene expression includes {gene_str}.",
        "{gene_str} expression was observed in diseased tissue from {disease_status}.",
        "A single-cell RNA-seq from {disease_status} reveals expression of {gene_str}.",
        "Expression profile {gene_str} comes from a cell within {disease_status} tissue.",
        "Under {disease_status}, cells express genes such as {gene_str}.",
        ],
}
